version: "3.9"
services:
  web:
    restart: unless-stopped
    build: 
      context: ./
    ports:
      - "8000:3011"
    depends_on: 
    - mongo_db
    environment:
      - DB_URI=mongodb://root:testpassword@mongo_db:27017 
    volumes:
        - "./:/home/app"
  mongo_db:
    ports:
      - 27017:27017
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpassword

    # mongodb://root:testpassword@localhost:27017 

    volumes:
      - ./mongo_db:/data/db
    
# docker-compose up --build --force-recreate  
# docker-compose up