version : '3.9'

services: 
  #Mongodb service 
  api: &node-wednesday
    image: rahulitobuzz/ec2-app
    build: .
    ports: 
    - 3011:3011
    environment: 
      SERVER_PORT: 3011
      SERVER_HOST: 'http://mongo_db'
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_HOST: 'mongo_db'
      DB_PORT: '27017'
      DB_URI: 'mongodb://mongo_db:27017/'
    depends_on: 
    - mongo_db
    volumes: 
       - ./nodeVol:/data/
  mongo_db: 
   container_name: db_container
   image: mongo:latest
   restart: always
   volumes: 
    - ./mongo_db:/data/db
 