name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
  
env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: asia-east1
  SERVICE_NAME: shopping-cart-backend

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          project_id: $PROJECT_ID
          export_default_credentials: true
          version: "318.0.0"
        
 