# .github/workflows/deploy.yaml
name: Deploy to Google App Engine
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: asia-east1
  SERVICE_NAME: shopping-cart-backend

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@v1
        with:
          credentials: ${{ secrets.GCR_SA_KEY }}
